// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.FRC36202017DaVincisCode.subsystems;

import org.usfirst.frc3620.FRC36202017DaVincisCode.RobotMap;
import org.usfirst.frc3620.FRC36202017DaVincisCode.commands.*;
import org.usfirst.frc3620.FRC36202017DaVincisCode.Robot;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class GearSubsystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftRightTalon = RobotMap.gearSubsystemLeftRightTalon;
    private final SpeedController tiltTalon = RobotMap.gearSubsystemTiltTalon;
    private final DoubleSolenoid gearPlunger = RobotMap.gearSubsystemGearPlunger;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    double gearShiftSpeed;
    double gearRotatorSpeed;
   
    
    public void shiftGear(double gearShiftRightSpeed, double gearShiftLeftSpeed){
    	if(Robot.oi.operatorJoystick.getRawAxis(3)> .2){
    		leftRightTalon.set(-gearShiftRightSpeed);
    	}
    	else if(Robot.oi.operatorJoystick.getRawAxis(2)< -.2){
    	leftRightTalon.set(gearShiftLeftSpeed);
    	}
    	else{
    		leftRightTalon.set(0);
    	}
    }
    
    public void rotateGearUp(){
    	tiltTalon.set(.75);
    }
    public void rotateGearDown(){
    	tiltTalon.set(-.75);
    }
    
    public void plungeGear(){
    	gearPlunger.set(Value.kForward);
    }
   
    public void retractGearPlunger(){
    	gearPlunger.set(Value.kReverse);
    }
    
    public void stopGearPlunger(){
    	gearPlunger.set(Value.kOff);
    }
    
    public void stopGearShift(){
    	leftRightTalon.set(0);
    	}
    
    public void stopGearRotate(){
    	tiltTalon.set(0);
    	}
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        setDefaultCommand(new ShiftGearCommand());
    }
}

