package org.usfirst.frc3620.FRC36202017DaVincisCode.commands;

import org.slf4j.Logger;
import org.usfirst.frc3620.FRC36202017DaVincisCode.Robot;
import org.usfirst.frc3620.logger.EventLogging;
import org.usfirst.frc3620.logger.EventLogging.Level;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class FeedShooterCommand extends Command {

	Logger logger = EventLogging.getLogger(getClass(), Level.INFO);
	 public FeedShooterCommand() {

		    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

		    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		    }

		    Timer timer = new Timer();
		    boolean canIShoot;
		    double impellerPower=0;
		    
		    
		    protected void initialize() {
		    	logger.info("Feeding shooter");
		    	canIShoot=Robot.shooterSubsystem.isShooterSpunUp();
		    	impellerPower=edu.wpi.first.wpilibj.Preferences.getInstance().getDouble("Impeller Power", 1);;
		    }
		    protected void execute() {
//		    	if(canIShoot)
		    		Robot.shooterSubsystem.runImpeller(impellerPower); 	
		    }
		    protected boolean isFinished() {
//		    	if  (!canIShoot) {
//					return true;
//				}
//		    	else{
//		    	return false;
//		    	}
		    	return false;
		    }
		    protected void end() {
		    	
		    	Robot.shooterSubsystem.runImpeller(0);
		    }
		    // subsystems is scheduled to run
		    protected void interrupted() {
		    	end();
		    }
}
