// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.FRC36202017DaVincisCode;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon subsystem1CANTalon1;
    public static SpeedController subsystem1SpeedController1;
    public static SpeedController subsystem2SpeedController1;
    public static SpeedController subsystem2SpeedController2;
    public static SpeedController subsystem2SpeedController3;
    public static SpeedController subsystem2SpeedController4;
    public static RobotDrive subsystem2RobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        subsystem1CANTalon1 = new CANTalon(0);
        LiveWindow.addActuator("Subsystem 1", "CAN Talon 1", subsystem1CANTalon1);
        
        subsystem1SpeedController1 = new Talon(0);
        LiveWindow.addActuator("Subsystem 1", "Speed Controller 1", (Talon) subsystem1SpeedController1);
        
        subsystem2SpeedController1 = new Talon(1);
        LiveWindow.addActuator("Subsystem 2", "Speed Controller 1", (Talon) subsystem2SpeedController1);
        
        subsystem2SpeedController2 = new Talon(2);
        LiveWindow.addActuator("Subsystem 2", "Speed Controller 2", (Talon) subsystem2SpeedController2);
        
        subsystem2SpeedController3 = new Talon(3);
        LiveWindow.addActuator("Subsystem 2", "Speed Controller 3", (Talon) subsystem2SpeedController3);
        
        subsystem2SpeedController4 = new Talon(4);
        LiveWindow.addActuator("Subsystem 2", "Speed Controller 4", (Talon) subsystem2SpeedController4);
        
        subsystem2RobotDrive41 = new RobotDrive(subsystem2SpeedController1, subsystem2SpeedController2,
              subsystem2SpeedController3, subsystem2SpeedController4);
        
        subsystem2RobotDrive41.setSafetyEnabled(true);
        subsystem2RobotDrive41.setExpiration(0.1);
        subsystem2RobotDrive41.setSensitivity(0.5);
        subsystem2RobotDrive41.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
